steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/brandai-36abd/gcp-pipeline-demo/gcp-pipeline-demo:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/brandai-36abd/gcp-pipeline-demo/gcp-pipeline-demo:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'gcp-pipeline-demo'
      - '--image'
      - 'us-central1-docker.pkg.dev/brandai-36abd/gcp-pipeline-demo/gcp-pipeline-demo:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NODE_ENV=production'
      - '--set-secrets'
      - 'DB_SECRET_NAME= demo_secrets:latest'
      - '--add-cloudsql-instances'
      - '${_INSTANCE_CONNECTION_NAME}'

images:
  - 'us-central1-docker.pkg.dev/brandai-36abd/gcp-pipeline-demo/gcp-pipeline-demo:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _INSTANCE_CONNECTION_NAME: '699656816818:us-central1:gcp-demo-db'
